apiVersion: apps/v1
   
kind: Deployment
   
metadata:
   
  labels:
   
    app.kubernetes.io/name: load-balancer-reverseproxy
   
  name: udagram-reverseproxy
   
spec:
   
  replicas: 2
   
  selector:
   
    matchLabels:
   
      app.kubernetes.io/name: load-balancer-reverseproxy
   
  template:
   
    metadata:
   
      labels:
   
        app.kubernetes.io/name: load-balancer-reverseproxy
   
    spec:
   
      containers:
   
      - image: vickytho/udagram-reverseproxy
   
        name: udagram-reverseproxy
   
        ports:
   
        - containerPort: 8080