language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - docker image prune --all -y

script:

  - docker build -t udagram-reverseproxy ./reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag reverseproxy vickytho/reverseproxy:v1
  - docker tag udagram-api-user vickytho/udagram-api-user:v1
  - docker tag udagram-api-feed vickytho/udagram-api-feed:v1
  - docker tag udagram-frontend vickytho/udagram-frontend:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vickytho/reverseproxy:v1
  - docker push vickytho/udagram-api-user:v1
  - docker push vickytho/udagram-api-feed:v1
  - docker push vickytho/udagram-frontend:v1