language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy vickytho/reverseproxy:latest
  - docker tag udagram-api-user vickytho/udagram-api-user:latest
  - docker tag udagram-api-feed vickytho/udagram-api-feed:latest
  - docker tag udagram-frontend vickytho/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vickytho/reverseproxy:latest
  - docker push vickytho/udagram-api-user:latest
  - docker push vickytho/udagram-api-feed:latest
  - docker push vickytho/udagram-frontend:latest
